/*
   This file was generated automatically by the Mojo IDE version B1.3.5.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module display_2 (
    input clk,
    input rst,
    input [255:0] pattern,
    output reg [7:0] ledmatrix
  );
  
  
  
  localparam ONE_state = 3'd0;
  localparam TWO_state = 3'd1;
  localparam THREE_state = 3'd2;
  localparam FOUR_state = 3'd3;
  localparam START_state = 3'd4;
  
  reg [2:0] M_state_d, M_state_q = START_state;
  reg [3:0] M_i_d, M_i_q = 1'h0;
  reg [3:0] M_j_d, M_j_q = 1'h0;
  reg [3:0] M_k_d, M_k_q = 1'h0;
  reg [15:0] M_time_d, M_time_q = 1'h0;
  
  always @* begin
    M_state_d = M_state_q;
    M_time_d = M_time_q;
    M_j_d = M_j_q;
    M_k_d = M_k_q;
    M_i_d = M_i_q;
    
    ledmatrix = 8'h00;
    
    case (M_state_q)
      START_state: begin
        M_i_d = 4'hf;
        M_j_d = 4'hf;
        M_k_d = 1'h0;
        M_time_d = 1'h0;
        M_state_d = ONE_state;
      end
      ONE_state: begin
        ledmatrix[4+0-:1] = 1'h1;
        ledmatrix[7+0-:1] = 1'h0;
        ledmatrix[5+0-:1] = 1'h0;
        ledmatrix[6+0-:1] = clk - 1'h1;
        if (M_j_q == 1'h0) begin
          M_state_d = THREE_state;
          M_j_d = 4'hf;
        end else begin
          M_j_d = M_j_q - 1'h1;
        end
      end
      THREE_state: begin
        ledmatrix[3+0-:1] = M_k_q[0+0-:1];
        ledmatrix[2+0-:1] = M_k_q[1+0-:1];
        ledmatrix[1+0-:1] = M_k_q[2+0-:1];
        ledmatrix[0+0-:1] = M_k_q[3+0-:1];
        ledmatrix[4+0-:1] = 1'h1;
        ledmatrix[7+0-:1] = 1'h0;
        ledmatrix[5+0-:1] = pattern[(M_i_q)*16+(M_j_q)*1+0-:1];
        ledmatrix[6+0-:1] = clk - 1'h1;
        if (M_j_q == 1'h0) begin
          M_state_d = FOUR_state;
          M_j_d = 4'hf;
        end else begin
          M_j_d = M_j_q - 1'h1;
        end
      end
      FOUR_state: begin
        ledmatrix[3+0-:1] = M_k_q[0+0-:1];
        ledmatrix[2+0-:1] = M_k_q[1+0-:1];
        ledmatrix[1+0-:1] = M_k_q[2+0-:1];
        ledmatrix[0+0-:1] = M_k_q[3+0-:1];
        ledmatrix[4+0-:1] = 1'h0;
        ledmatrix[7+0-:1] = 1'h1;
        M_time_d = M_time_q + 1'h1;
        if (M_time_q == 16'h61a8) begin
          M_time_d = 1'h0;
          if (M_i_q == 1'h0) begin
            M_state_d = START_state;
          end else begin
            M_i_d = M_i_q - 1'h1;
            M_k_d = M_k_q + 1'h1;
            M_state_d = ONE_state;
          end
        end
      end
    endcase
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_state_q <= 3'h4;
    end else begin
      M_state_q <= M_state_d;
    end
  end
  
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_i_q <= 1'h0;
      M_j_q <= 1'h0;
      M_k_q <= 1'h0;
      M_time_q <= 1'h0;
    end else begin
      M_i_q <= M_i_d;
      M_j_q <= M_j_d;
      M_k_q <= M_k_d;
      M_time_q <= M_time_d;
    end
  end
  
endmodule
