/*
   This file was generated automatically by the Mojo IDE version B1.3.5.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module paddleB_7 (
    input clk,
    input rst,
    input playing,
    input btnLeft,
    input btnRight,
    output reg [3:0] padB
  );
  
  
  
  localparam GAMEON_state = 2'd0;
  localparam GAMESTART_state = 2'd1;
  localparam LEFTBTNWAIT_state = 2'd2;
  localparam RIGHTBTNWAIT_state = 2'd3;
  
  reg [1:0] M_state_d, M_state_q = GAMESTART_state;
  reg [3:0] M_padBtemp_d, M_padBtemp_q = 1'h0;
  
  always @* begin
    M_state_d = M_state_q;
    M_padBtemp_d = M_padBtemp_q;
    
    padB = M_padBtemp_q;
    
    case (M_state_q)
      GAMESTART_state: begin
        M_padBtemp_d = 4'he;
        M_state_d = GAMEON_state;
      end
      GAMEON_state: begin
        if (playing == 1'h1) begin
          if (btnLeft == 1'h0 && M_padBtemp_q > 1'h1) begin
            M_padBtemp_d = M_padBtemp_q - 1'h1;
            padB = M_padBtemp_q;
            M_state_d = LEFTBTNWAIT_state;
          end
        end
      end
      LEFTBTNWAIT_state: begin
        if (playing == 1'h1) begin
          if (btnLeft == 1'h1) begin
            M_state_d = GAMEON_state;
          end
        end
      end
      RIGHTBTNWAIT_state: begin
        if (playing == 1'h1) begin
          if (btnRight == 1'h1) begin
            M_state_d = GAMEON_state;
          end
        end
      end
    endcase
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_state_q <= 1'h1;
    end else begin
      M_state_q <= M_state_d;
    end
  end
  
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_padBtemp_q <= 1'h0;
    end else begin
      M_padBtemp_q <= M_padBtemp_d;
    end
  end
  
endmodule
