/*
   This file was generated automatically by the Mojo IDE version B1.3.5.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module score_8 (
    input playing,
    input [3:0] ballY,
    output reg [3:0] scoreA,
    output reg [3:0] scoreB
  );
  
  
  
  reg scoreAtemp;
  
  reg scoreBtemp;
  
  always @* begin
    scoreAtemp = 1'h0;
    scoreBtemp = 1'h0;
    scoreA = 1'h0;
    scoreB = 1'h0;
    if (playing == 1'h1) begin
      if (ballY == 1'h0) begin
        scoreBtemp = scoreBtemp + 1'h1;
        scoreB = scoreBtemp;
      end else begin
        if (ballY == 4'hf) begin
          scoreAtemp = scoreAtemp + 1'h1;
          scoreA = scoreAtemp;
        end
      end
    end
  end
endmodule
