/*
   This file was generated automatically by the Mojo IDE version B1.3.5.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module logic_4 (
    input btnStart,
    input [3:0] scoreA,
    input [3:0] scoreB,
    output reg playing
  );
  
  
  
  always @* begin
    playing = 1'h1;
    if (btnStart == 1'h0 && scoreA < 3'h7 && scoreB < 3'h7) begin
      playing = 1'h1;
    end
  end
endmodule
