/*
   This file was generated automatically by the Mojo IDE version B1.3.5.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module adder_28 (
    input [5:0] alufn,
    input [7:0] a,
    input [7:0] b,
    output reg [7:0] sum_output,
    output reg z,
    output reg v,
    output reg n,
    output reg sub_overflow
  );
  
  
  
  reg [8:0] sum;
  
  reg [8:0] sub_sum;
  
  always @* begin
    
    case (alufn[0+1-:2])
      2'h0: begin
        sub_sum = a - b;
        sum = a + b;
      end
      2'h1: begin
        sub_sum = a - b;
        sum = a - b;
      end
      2'h2: begin
        sub_sum = a - b;
        sum = a * b;
      end
      2'h3: begin
        sub_sum = a - b;
        sum = a - (a / b * b);
      end
      default: begin
        sub_sum = a - b;
        sum = a + b;
      end
    endcase
    sum_output = sum[0+7-:8];
    sub_overflow = (a[7+0-:1] & ~b[7+0-:1] & (~sub_sum[7+0-:1])) | ((~a[7+0-:1]) & (b[7+0-:1]) & sub_sum[7+0-:1]);
    v = (a[7+0-:1] & b[7+0-:1] & (~sum[7+0-:1])) | ((~a[7+0-:1]) & (~b[7+0-:1]) & sum[7+0-:1]);
    n = sub_sum[7+0-:1];
    z = (~|sub_sum);
  end
endmodule
