/*
   This file was generated automatically by the Mojo IDE version B1.3.5.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module compare_29 (
    input [5:0] alufn,
    input z,
    input sub_overflow,
    input n,
    output reg [7:0] cmp_output
  );
  
  
  
  reg cmp;
  
  always @* begin
    
    case (alufn[1+1-:2])
      2'h1: begin
        cmp = z;
      end
      2'h2: begin
        cmp = n ^ sub_overflow;
      end
      2'h3: begin
        cmp = z | (n ^ sub_overflow);
      end
      default: begin
        cmp = 1'h0;
      end
    endcase
    cmp_output[0+0-:1] = cmp;
    cmp_output[1+6-:7] = 7'h00;
  end
endmodule
