/*
   This file was generated automatically by the Mojo IDE version B1.3.5.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module drawing_3 (
    input [3:0] ballX,
    input [3:0] ballY,
    input [15:0] padA,
    input [15:0] padB,
    input [1:0] playing,
    output reg [255:0] pattern
  );
  
  
  
  integer i;
  
  always @* begin
    if (playing == 1'h1) begin
      for (i = 1'h0; i < 5'h10; i = i + 1) begin
        pattern[(i)*16+15-:16] = 16'hffff;
      end
      pattern[0+15-:16] = ~padA;
      pattern[240+15-:16] = ~padB;
      pattern[(ballY)*16+(ballX)*1+0-:1] = 1'h0;
    end else begin
      if (playing == 2'h2) begin
        pattern = 256'hffffffffff1fffe7ffdfffe7811fafffaf0781ffff07ffdfff5fff07ffffffff;
      end else begin
        if (playing == 2'h3) begin
          pattern = 256'hffffffffff8ffff3ffeffff3808fb6ffb683c9ffff83ffdfffefff83ffffffff;
        end else begin
          pattern = 256'hffffefff1fffe87ffbd598556fc1087ffb494875afc10f7ff8c1ff75ffc1ffff;
        end
      end
    end
  end
endmodule
