/*
   This file was generated automatically by the Mojo IDE version B1.3.5.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module score_display_11 (
    input clk,
    input rst,
    input [6:0] scoreAdisplay,
    input [6:0] scoreBdisplay,
    output reg [6:0] score_display,
    output reg [3:0] score_sel
  );
  
  
  
  reg M_counter_d, M_counter_q = 1'h0;
  
  reg [15:0] digitsel;
  
  always @* begin
    M_counter_d = M_counter_q;
    
    score_display = 7'h00;
    score_sel = 4'h0;
    digitsel = 16'h7bde;
    M_counter_d = M_counter_q + 1'h1;
    if (M_counter_q == 1'h0) begin
      score_sel = digitsel[4+3-:4];
      score_display = scoreAdisplay;
    end else begin
      if (M_counter_q == 1'h1) begin
        score_sel = digitsel[8+3-:4];
        score_display = scoreBdisplay;
      end
    end
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_counter_q <= 1'h0;
    end else begin
      M_counter_q <= M_counter_d;
    end
  end
  
endmodule
